database:
  user: root
  password: 123456
  host: 47.117.136.250
  port: 3306
  name: blog
  disable_log: false
app:
  port: 8081
  mode: debug
logger:
  level: debug
  filename: run.log
  maxsize: 200
  max_age: 7
  max_backups: 10